### ISSUE TITLE
Shutters

### ISSUE THREAD

**Issue by Gerrett84** [planbnet/livisi_unofficial#10]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It would be great if you could add the shutter control. I would make myself available as a tester and test and carry out everything that is necessary ;-). I'd open a PR for it myself and add the code, but that's beyond my skills .
If not, you still have my biggest thanks for continuing here without Livisi :-)

### Describe the solution you'd like

Shutters Controll

### Describe alternatives you've considered

I can't think of an alternative here

### Additional context

I don't think it's necessary.

**Comment by planbnet** [comment]
I cannot do this - I don't even have window shutters (so even if I had access to the Livisi devices I couldn't test it), but I'd be happy to accept a PR from someone else (or backport changes from the official Livisi integration if they were implemented there).

**Comment by ThMFlive** [comment]
I get the additional roller shutter's today. So next week you can start.

**Comment by ThMFlive** [comment]
@acidburn78 I have the devices. Markus, please answer my mails to get them.

**Comment by Gerrett84** [comment]
@acidburn78 did you get it working? :-)

**Comment by planbnet** [comment]
Inspired by https://github.com/home-assistant/core/pull/101701#issuecomment-1752865585 I added experimental and untested support in commit 529953f - maybe someone will test it before I release a new version?

**Comment by Gerrett84** [comment]
> Inspired by [home-assistant/core#101701 (comment)](https://github.com/home-assistant/core/pull/101701#issuecomment-1752865585) I added experimental and untested support in commit [529953f](https://github.com/planbnet/livisi_unofficial/commit/529953f114cd4018e0909c6318a5471b29a3a4d4) - maybe someone will test it before I release a new version?

Awesome, I'll test it and report back

**Comment by Gerrett84** [comment]
It doesn't fully work yet. It is possible to move the shutter up and down. Stopping also works. Unfortunately, the current position feedback is still missing
![Screenshot_20231015-200403](https://github.com/planbnet/livisi_unofficial/assets/1213908/12ee8051-8d5e-432f-b605-9db603b7650a)

**Comment by planbnet** [comment]
Does the inital positioning (i.e. when starting HA) work? If not, then probably the code of the PR in the official repo doesn't work neither...
If it does: I've added debug code that outputs the correct property type. If you could update to the latest code, retry and send me the debug output, I should be able to fix it.

**Comment by Gerrett84** [comment]
No, the initial positioning doesn't Work.

**Comment by Gerrett84** [comment]
Still doesn't work. But I can now also control the shutter with the dimmer. However, the position is still “unknown”

**Comment by planbnet** [comment]
I've added a debug commit that logs all incoming messages as an error (so they will appear without any changes to your logging settings).

Would you install the latest commit, start HASS and change the Shutter state a few times (move up, down, etc)? You could also switch a few other devices (dimmer and anything that also might not yet be supported) so I have a log of all those messages that i cannot reproduce with my hardware...

**Comment by Gerrett84** [comment]
Looks like commit c848c06 solved the problem. Everything works now. Good job !
The dimmer has now been working since your last commit. Otherwise I don't have any other devices ;-)

`
2023-10-16 19:25:49.754 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.livisi.cover.LivisiShutter'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please create a bug report at https://github.com/planbnet/livisi_unofficial/issues

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Source: custom_components/livisi/livisi_websocket.py:65
Integration: Livisi Unofficial (documentation, issues)
First occurred: 19:31:35 (78 occurrences)
Last logged: 19:39:00

{"type": "StateChanged","namespace": "CosipDevices.RWE","desc": "/desc/device/ISR2.RWE/1.0/capability/RollerShutterActuator/event/StateChanged","source": "/capability/e53073c4f2f043c1b5adfed068a1095e","timestamp": "2023-10-17T17:36:13.866045Z","properties": {"shutterLevel": 0},"context": {"details": {}}}
{"type": "StateChanged","namespace": "CosipDevices.RWE","desc": "/desc/device/ISR2.RWE/1.0/capability/RollerShutterActuator/event/StateChanged","source": "/capability/e53073c4f2f043c1b5adfed068a1095e","timestamp": "2023-10-17T17:36:19.364630Z","properties": {"shutterLevel": 3},"context": {"details": {}}}
{"type": "StateChanged","namespace": "CosipDevices.RWE","desc": "/desc/device/ISR2.RWE/1.0/capability/RollerShutterActuator/event/StateChanged","source": "/capability/e53073c4f2f043c1b5adfed068a1095e","timestamp": "2023-10-17T17:36:23.216996Z","properties": {"shutterLevel": 0},"context": {"details": {}}}
{"type": "StateChanged","namespace": "CosipDevices.RWE","desc": "/desc/device/WMD.RWE/1.0/capability/MotionDetectionSensor/event/StateChanged","source": "/capability/63ade31d06b140cdbedb04cf96872b87","timestamp": "2023-10-17T17:36:33.440274Z","properties": {"motionDetectedCount": 168},"context": {"details": {}}}
{"type": "MotionDetected","namespace": "CosipDevices.RWE","desc": "/desc/device/WMD.RWE/1.0/capability/MotionDetectionSensor/event/MotionDetected","source": "/capability/63ade31d06b140cdbedb04cf96872b87","timestamp": "2023-10-17T17:36:33.442654Z","properties": {"luminance": 14},"context": {"details": {}}}`

**Comment by planbnet** [comment]
Thanks @Gerrett84 - I've released 1.7.0

**Comment by ThMFlive** [comment]
Thanks to @planbnet and @Gerrett84 for this update. It works very well. Very good job!

**Comment by MGODOIT** [comment]
Thanks you @planbnet and @Gerrett84 !
I'm very happy with it. Great Job!!

**Comment by Uli112Winsen** [comment]
Thank you @planbnet and @Gerrett84 !
I'm very happy with it. Great Job !!
