### ISSUE TITLE
Add Restart Button  SHC1

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#106]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

the SHC 1 have with the latest Firmware a bug in Ram so its after a while needed to restart SHC1.

With HA we can made automate it (when Ram 90%, then reboot SHC1)

@DanielHabenicht have done a pull request, but so i understand for SHC2

what you think @planbnet 

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by planbnet** [comment]
The is already handled in PR #89 and should support both SHC versions, but it currently has conflicts and is not yet merged.
