### ISSUE TITLE
Error requesting Livisi devices data

### ISSUE THREAD

**Issue by olli711** [planbnet/livisi_unofficial#108]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 115.4 GB
disk_used | 20.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Samba Backup (5.2.0), Samba share (12.3.1), motionEye (0.20.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 20
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28. März 2024 um 06:25
-- | --
current_recorder_run | 1. April 2024 um 17:19
estimated_db_size | 153.56 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, for some time now I have been receiving sporadic following messages. In one case, all thermostats were turned off. 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Quelle: helpers/update_coordinator.py:331
Integration: Livisi Unofficial (Dokumentation, Probleme)
Erstmals aufgetreten: 09:34:30 (16 Vorkommnisse)
Zuletzt protokolliert: 15:00:59

Error requesting Livisi devices data: [Errno 104] Connection reset by peer

This was followed by the following warning:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Quelle: custom_components/livisi/livisi_connector.py:238
Integration: Livisi Unofficial (Dokumentation, Probleme)
Erstmals aufgetreten: 09:34:30 (252 Vorkommnisse)
Zuletzt protokolliert: 15:41:38

Error loading capability
Error loading device
Error loading location

Edit: There seems to be some kind of problem with the SHC1. At the headquarters was the warning triangle. However, I can't reproduce the bug. In addition, a number of entities are unavailable, even though they react when used. E.g. window sensors. I can see in the history that they are off or on. However, the automations are not responding. After a restart of the system, everything seems to be running so far, but the Binay sensors of the motion detectors and window sensors have marked as unavailable

### Reproduction steps

1.can not reproduce 
2.
3.
...

### Debug logs

```text
none
```

**Comment by olli711** [comment]
I received this error message twice this week.

**Comment by planbnet** [comment]
Wo genau wird denn dieser Fehler angezegit? Im Log? Das ist doch völlig normal und absolut beabsichtigt... Wo ist das Problem?

**Comment by olli711** [comment]
Hi,

der Fehler wird in der Protokollansicht angezeigt. Was meinst Du mit völlig Normal und beabsichtigt?  

Es sieht bei mir danach aus, als würden diese Meldungen im Zusammenhang mit einer Error 2007 Meldung das aufhängen der SHC zu verursachen. Zufall?  Ich habe das etwas ausführlicher in meiner anderen Meldung geschrieben. 

Was genau sollen mir diese Meldungen sagen?

**Comment by planbnet** [comment]
Das bedeutet, dass die SHC nicht mehr antwortet. Mehr als einen Fehler ausgeben kann die Integration in dem Fall nicht tun.

**Comment by olli711** [comment]
okay, das ist natürlich klar. Dann muss der Fehler ja im Netz liegen.

**Comment by olli711** [comment]
Hi, 

bisher hatte ich keinen Ausfall mehr. Ich habe da eine Vermutung, die aber ausschließlich mit der Fritzbox zu tun har

**Comment by olli711** [comment]
Hi,

bisher hatte ich keinen Ausfall mehr. Ich habe da eine Vermutung, die aber ausschließlich mit der Fritzbox zu tun hat
