### ISSUE TITLE
Remove Livisi Unoffival

### ISSUE THREAD

**Issue by hschluet29** [planbnet/livisi_unofficial#114]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Logger: homeassistant.components.fritzbox_callmonitor
Quelle: components/fritzbox_callmonitor/__init__.py:48
Integration: AVM FRITZ!Box Call Monitor (Dokumentation, Probleme)
Erstmals aufgetreten: 18:37:16 (1 Vorkommnisse)
Zuletzt protokolliert: 18:37:16

Invalid authentication: Unable to perform operation. 401 Unauthorized (ERR_NONE) 401 Unauthorized ERR_NONE Webserver Mon, 22 Apr 2024 16:37:16 GMT

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:188
Erstmals aufgetreten: 18:37:11 (1 Vorkommnisse)
Zuletzt protokolliert: 18:37:11

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

Logger: homeassistant.components.cover
Quelle: helpers/entity_platform.py:744
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 18:37:36 (96 Vorkommnisse)
Zuletzt protokolliert: 18:37:42

Platform livisi does not generate unique IDs. ID 27d9c3d6d0484b9b8baa572e0d2f7bd4 already exists - ignoring cover.rollladen_strasse
Platform livisi does not generate unique IDs. ID 498cdf515e344ea9bfd286997c689d3b already exists - ignoring cover.rollladen_carport
Platform livisi does not generate unique IDs. ID 1826c8691ca24d229b613f299e6f7fca already exists - ignoring cover.rollladen_garten
Platform livisi does not generate unique IDs. ID e2920798fef54dd6a66a261644e60f8e already exists - ignoring cover.rollladen_terasse

### Describe the solution you'd like

Beseitigung des Problems

### Describe alternatives you've considered

keine

### Additional context

keiner

**Comment by planbnet** [comment]
Unfortunately, I cannot debug issues with the cover integration (as I don't have any), but I think this problem comes from a broken setup (maybe an update that went wrong). Removing the SHC and entities and then readding it should help in these cases. As long as they haven't been renamed, all entities will get the same name.
