### ISSUE TITLE
Livisi sent error code 2007

### ISSUE THREAD

**Issue by olli711** [planbnet/livisi_unofficial#118]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4854
Installed Version | 1.34.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 115.4 GB
disk_used | 17.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Samba Backup (5.2.0), Samba share (12.3.1), motionEye (0.20.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 20
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20. April 2024 um 20:57
-- | --
current_recorder_run | 24. April 2024 um 07:15
estimated_db_size | 144.22 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi,

I get this error displayed regularly. This is followed by another message about an expiring token, which I attach here. These mistakes ALWAYS come together

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Quelle: custom_components/livisi/livisi_connector.py:168
Integration: Livisi Unofficial (Dokumentation, Probleme)
Erstmals aufgetreten: 07:17:00 (1 Vorkommnisse)
Zuletzt protokolliert: 07:17:00

Livisi sent error code 2007 after token request

and here the next one:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Quelle: helpers/update_coordinator.py:347
Integration: Livisi Unofficial (Dokumentation, Probleme)
Erstmals aufgetreten: 07:17:00 (1 Vorkommnisse)
Zuletzt protokolliert: 07:17:00

Error fetching Livisi devices data: The lifetime of the token has expired.

### Reproduction steps

..
2.
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by olli711** [comment]
Seid Anfang dieser Woche kommen beide  Meldungen jeden Tag.

**Comment by planbnet** [comment]
I cannot reproduce this problem (and I don't even see how it is a problem at all, just a bit noise in the logs once a day).
