### ISSUE TITLE
Battery level indicators not working 

### ISSUE THREAD

**Issue by Gerrett84** [planbnet/livisi_unofficial#12]
### System Health details

N/a

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Battery level indicators doesn't seem to work.
Today I received a notification via the Livisi app that the battery of a motion detector needs to be replaced. However, the status in Hassio is still "normal".

### Reproduction steps

Not necessary, the battery needs to be replaced Status is still pending.

### Debug logs

```text
I'll submit if necessary.
```

**Comment by planbnet** [comment]
As I noted, I have to wait until a battery runs out on my setup to check if the code is working, at the moment it is fully untested (and probably does not work if you experienced this problem)

**Comment by planbnet** [comment]
This should be fixed in the latest release.

**Comment by Gerrett84** [comment]
Yep, Works now :-)
