### ISSUE TITLE
Remote does not work when i use short press

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#151]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

ich schreibs besser in deutsch, kann ich es besser erklären.

Ich steuere mit der Livisi Fernbedienung meine Tasmota Steckdosen, aber auch ein Livisi Dimmerstecker via Automation in HA

es gibt ja da 2 Optionen, "Taste xx gedrückt" und " Taste xx lang gedrückt"

Um die Steckdosen zu steuern muss ich auf "Taste xx lang drücken" zurückgreifen, die andere Variante reagiert nicht.

vlt. kannst Du das mal reproduzieren in dem Du mal ne Automation erstellst und versuchst eine Steckdose zu steuern.

hier der genutzte Yaml Code am Beispiel Taste 3 was meine LED-Strips via Tasmota Stecker steuert...

alias: Taste 3 LED Komplett
description: ""
trigger:
  - platform: device
    device_id: 1df04a548650a40d32a36c881754e5a0
    domain: livisi
    type: button_long_pressed
    subtype: button_2
condition: []
action:
  - type: toggle
    device_id: d9847a376921fdd387a28d23c61195f1
    entity_id: bb96f1ea7990574a4afc8deee979628e
    domain: switch
  - type: toggle
    device_id: 678fa14bc62fc0e587ba3288c1d7bebc
    entity_id: 974b62dc5d2c5e2ed785a8381f9ab61a
    domain: switch
mode: single

und hier als Taste 2 wo einen Livisi Dimmer steuert:

alias: Taste 2 Stehleuchte
description: ""
trigger:
  - platform: device
    device_id: 1df04a548650a40d32a36c881754e5a0
    domain: livisi
    type: button_long_pressed
    subtype: button_1
condition: []
action:
  - target:
      entity_id:
        - light.stehleuchte_dimm
    data:
      brightness_pct: 20
    action: light.toggle
mode: single

wie gesagt, alles funktioniert nur mit "Taste xx lang gedrückt" Vlt. hast Du mal Zeit Dir das anzuschauen

### Reproduction steps

1.
2.
3.
...
.

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by planbnet** [comment]
Die "normale" 8-Tasten Fernbedienung? Bei der habe ich die ganz normalen Button Presses erfolgreich gemappt:

![image](https://github.com/user-attachments/assets/a316baf2-0099-4c6e-a225-d5b09dc2ee4f)

Ist das vielleicht irgendeine Einstellung, die man in der Livisi Zentrale ändern kann, dass kurze Tastendrücke nicht gesendet werden oder so?

**Comment by metaiiica** [comment]
keine Ahnung, jedenfalls funktioniert deine Variante nicht. Nur wenn ich auf "lang gedrückt" verwende
