### ISSUE TITLE
Battery unknown

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#28]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

if Battery full from a Device, it will displayed unknown. And if Battery low, it will display on.

can it make it display correctly full or low ?

### Describe the solution you'd like

see Screenshot

https://ibb.co/LJgtYTh

### Describe alternatives you've considered

n/A

### Additional context

n/A

**Comment by Gerrett84** [comment]
It is displayed correctly for me. The condition should show as 'normal' if the battery has sufficient charge. Although I haven't figured out when the status is shown as low in Hassio. A device keeps showing up as 'low' in the Livisi app Reported, but in Hassio he is still on 'nornal'

**Comment by metaiiica** [comment]
> It is displayed correctly for me. The condition should show as 'normal' if the battery has sufficient charge. Although I haven't figured out when the status is shown as low in Hassio. A device keeps showing up as 'low' in the Livisi app Reported, but in Hassio he is still on 'nornal'

for me it displayed unknown when full. See screenshot.

What for SHC you are use?

**Comment by ThMFlive** [comment]
I have the same error. I don't get a battery indicator either.

SHC 2.0 with new firmware 8.17 - 1.2.43.475

**Comment by planbnet** [comment]
Yep, you're right. I broke this with the rewrite. Fixed in 1.4.2
