### ISSUE TITLE
After HA update to 9.0, Livisi will not load

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#29]
### System Health details

just update HA Core to 9.0 

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration wont load

### Reproduction steps

1. update HA Core to 9.0

### Debug logs

```text
Logger: homeassistant.config_entries
Source: helpers/device_registry.py:531
First occurred: 07:29:26 (1 occurrences)
Last logged: 07:29:26

Error setting up entry SHC Classic for livisi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/__init__.py", line 38, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 531, in async_get_or_create
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Can't link device to unknown config entry 914101049075
```

**Comment by metaiiica** [comment]
Livisi official has this issue too

**Comment by planbnet** [comment]
My HA updated automatically to 2023.9 this night and I have the same problem. I'll have a look at it this evening..
