### ISSUE TITLE
BRC8 Smarthome Fernbedienung support

### ISSUE THREAD

**Issue by MGODOIT** [planbnet/livisi_unofficial#44]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

In the code i found the battery powered BRC8-remote-control with 8 buttons.
But in HA there is only 1 generic button. It does not reacts on any button-press.
Would be great :-)

### Describe the solution you'd like

8 events in HA, each for one pressed button.
additional long-press events would be great, too.

### Describe alternatives you've considered

Hints to do it myselfe (not a very good py-coder!)

### Additional context

Can i help with some logs of the 8 button-pressed from SHC or HA? or something like that?
Where to catch the right logs?

**Comment by metaiiica** [comment]
BRC8 can only report a pressed Button. But can not report a specific Button.

**Comment by planbnet** [comment]
The event entities in HA do not yet support modifiers, so there would need to be 16 different events… This feature is quite new in HA and I‘m unsure how it is supposed to be used. 

You need to use the device triggers. Just open the device and click + besides Automations. There you can add automations for all buttons (and long presses)

**Comment by MGODOIT** [comment]
Found it. Thank you for your advice.

![image](https://github.com/planbnet/livisi_unofficial/assets/38396702/3921e262-c884-4b00-b1d6-f7fde0223fd9)
