### ISSUE TITLE
Tasten der Rolladensteuerung 

### ISSUE THREAD

**Issue by marcel51090** [planbnet/livisi_unofficial#48]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hallo zusammen,

Kann es sein das die Tasten der rolladensteuerungen nicht unterstützt werden oder bin ich nur zu doof es zu finden? 

### Describe the solution you'd like

Als Beispiel würde ich gerne mit dem Tastendruck das Rollo öffnen und gleichzeitig eine Lampe ausschalten.
Ist das möglich?

Vielen dank für die ganze Arbeit die ihr euch macht. Das ist klasse das die Rollos hierüber betrieben werden können. 

Viele Grüße Marcel 

### Describe alternatives you've considered

Aktuell lasse ich diese Funktion über die livisi zentrale laufen, würde dies aber gern verhindern. 

### Additional context

.

**Comment by planbnet** [comment]
Eventuell reicht es, die Steuerung zu `BUTTON_COUNT = {"BRC8": 8, "ISC2": 2, "ISS2": 2, "WSC2": 2}` in der const.py hinzuzufügen. Den Code habe ich so generisch geschrieben, dass dann dafür Device Trigger erstellt werden. Das müsste aber jemand ausprobieren, der das Device besitzt.

**Comment by MGODOIT** [comment]
Ich habe "ISR2": 2 eingefügt und dann erschein unter Automatisierung zusätzlich Taste 1 & 2. 

![image](https://github.com/planbnet/livisi_unofficial/assets/38396702/99573c18-809f-40c2-95a1-8198952d559c)

**Comment by planbnet** [comment]
Ja, dass die Auslöser erzeugt werden ist schon mal richtig... Funktionieren die Events denn auch?

**Comment by MGODOIT** [comment]
Bin auf Dienstreise, probiere ich am WE.

**Comment by MGODOIT** [comment]
Ja läuft bei mir:

![image](https://github.com/planbnet/livisi_unofficial/assets/38396702/876ec801-3554-4ac2-a3b7-28a3a01bbf60)

**Comment by planbnet** [comment]
Great. Supported in 1.7.1

**Comment by marcel51090** [comment]
Super das dass so schnell geklappt hat. 
Vielen Dank dafür. 🙏

Habe da gar nicht dran gedacht, aber wäre es nicht sinnvoll, dies auch für die normalen Lichtschalter bzw Dimmer einzufügen? 

Gruß Marcel

**Comment by planbnet** [comment]
Hi,

für die Lichtschalter ist es ja schon drin, deswegen ging das ja so einfach das einzubauen.

Gruß,
Felix

**Comment by marcel51090** [comment]
Achso okay.. 
habe nur Dimmer im Einsatz daher dachte ich es fehlt vielleicht noch bei beiden. 
Aber dann sind es nur die Dimmer. 

Gruß
