### ISSUE TITLE
Change WDS_DEVICE_TYPES to  Final = ["WDS", "BT-WDS"]

### ISSUE THREAD

**Issue by kappuchino** [planbnet/livisi_unofficial#50]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I've set up the medion bluetooth sensors, they work in the local smarthome but don't show up in the home assistant version.

### Describe the solution you'd like

Change WDS_DEVICE_TYPES: Final = ["WDS"] to WDS_DEVICE_TYPES: Final = ["WDS", "BT-WDS"].

I did that locally and it just worked. As in: Completely. 

### Describe alternatives you've considered

None, since it just worked changing that...

### Additional context

If you need such a divice, I'm happy to send out one for testing.

**Comment by planbnet** [comment]
Done.
