### ISSUE TITLE
Button for ISD2

### ISSUE THREAD

**Issue by aseeus** [planbnet/livisi_unofficial#51]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Would be great to also add buttons for ISD2 in const.py

### Describe the solution you'd like

In const.py please add "ISD2" in BUTTON_DEVICE_TYPES and "ISD2": 2 in BUTTON_COUNT

BUTTON_DEVICE_TYPES: Final = ["ISS2", "WSC2", "ISC2", "BRC8", "ISD2"]

and

BUTTON_COUNT = {"BRC8": 8, "ISC2": 2, "ISS2": 2, "WSC2": 2, "ISR2": 2, "ISD2": 2}

I have tested it and it works without any problems

### Describe alternatives you've considered

---

### Additional context

![ISD2 Button in cont py](https://github.com/planbnet/livisi_unofficial/assets/105172359/fc5cba0d-b137-470d-ae25-b9be62b9e7a5)

**Comment by planbnet** [comment]
Done

**Comment by aseeus** [comment]
Thanks a lot. Really appreciate all your effort
