### ISSUE TITLE
Rolladen gruppieren

### ISSUE THREAD

**Issue by Jannilein** [planbnet/livisi_unofficial#59]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hallo, wie kann ich mehrere Rolladen gleichzeitg steuern, am besten auch noch über Nabu Casa Alexa Sprachbefehl?

### Describe the solution you'd like

H

### Describe alternatives you've considered

E

### Additional context

LP

**Comment by planbnet** [comment]
Das musst du in Home Assistant selbst tun. Mit der Livisi Integration hat das nichts zu tun.
