### ISSUE TITLE
Add electricity meter

### ISSUE THREAD

**Issue by stefanhintermayr** [planbnet/livisi_unofficial#75]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I don't see how much electricity my house draws or how much the solar system feeds into it.

### Describe the solution you'd like

As a further device, include the reading unit of the electricity meter, which is a device from Livisisi / RWE / Innogy.
This bi-directional meter measures the purchase (supply meter) and the feed-in (feed-in meter).
There is also another measuring unit in my installation for the production counter of the PV system. Both hang wirelessly via a USB stick at the Livisi headquarters (SHC 2.0).

### Describe alternatives you've considered

Alternatively, I could of course exchange the entire reading head for another system. But I don't actually want that.

### Additional context

I have no further comments at the moment.

**Comment by planbnet** [comment]
I don't have the electricity meter, but I'm open for pull requests..

**Comment by stefanhintermayr** [comment]
Help me, I see the function to create a "pull request", but I don't know how to proceed. Can I then test for you?
P.s.: Do you also speak German? Do you have to write English here?

**Comment by planbnet** [comment]
Ja, ich spreche Deutsch, aber falls diese Integration irgendwann mal Teil des offiziellen HomeAssistant wird, macht es Sinn, sämtliche Doku in Englisch zu haben... 
Was ich meinte ist, dass ich dieses Feature nicht implementieren kann, weil ich das entprechende Gerät nicht besitze (und auch keinen Bedarf habe, ich messe den Strom mit vzlogger). Falls jemand anders das programmieren, testen und zu dieser Integration hinzufügen möchte, kann er/sie das über einen Pull Request tun..

**Comment by planbnet** [comment]
Closing this as this is nothing I can implement...

**Comment by planbnet** [comment]
@stefanhintermayr Has collected data, see commit [dc1c158](https://github.com/planbnet/livisi_unofficial/commit/dc1c158891913262334615e401285389f6fa1742)

It should be possible to implement this as sensors

**Comment by planbnet** [comment]
@stefanhintermayr Please test the energy_sensors branch

**Comment by stefanhintermayr** [comment]
Done.
