### ISSUE TITLE
Open and close the roller shutters in a group in percentage terms with Alexa...

### ISSUE THREAD

**Issue by stefanhintermayr** [planbnet/livisi_unofficial#76]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

If several roller shutters are to be opened or closed grouped via HA via Alexa, Alexa says this is not supported by the group.
But it worked with the original Livisi skill. It is also possible to switch roller shutters on/off using the HA skill, but in my opinion that is wrong.

### Describe the solution you'd like

Group shutters or switch them in rooms in percentages in Alexa. deactivate the on/off of roller shutters, because if they are assigned to the rooms in Alexa and you say "Room off", the roller shutters always go down.

### Describe alternatives you've considered

currently none

### Additional context

I have no further comments at the moment.

**Comment by planbnet** [comment]
But as I don't have any roller shutters, I cannot even understand what you mean...
"But it worked with the original Livisi skill" - sounds more like a problem with how covers are implementes in HA, not with this integration.
