### ISSUE TITLE
Room Thermostat: Automatic and Manual mode

### ISSUE THREAD

**Issue by cagcoach** [planbnet/livisi_unofficial#77]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to use all the features of the room thermostat (https://www.amazon.de/-/en/10267400/dp/B01LDIJC6U) which by now only supports setting up temerature but not switching between manual and automatic

### Describe the solution you'd like

I would like to implement those features identical to the implementation of the homematic thermostat, where the hvac-modes are used. there OFF represents off (4.5 °C), HEAT represents Manual mode and AUTO represents Automatic.

### Describe alternatives you've considered

in contrast to the homematic implementation OFF could stay as now for set_tempreture<target_temperature. I still would consider this as inconsitant to homematic thus less desirable.

### Additional context

Here is the content of the post-request to "action" on port 8080, which the web frontend does
<img width="550" alt="Bildschirmfoto 2024-02-09 um 20 43 57" src="https://github.com/planbnet/livisi_unofficial/assets/9169292/2551c46f-608b-4478-9e15-d8c7bc6947ae">
<img width="557" alt="Bildschirmfoto 2024-02-09 um 20 44 31" src="https://github.com/planbnet/livisi_unofficial/assets/9169292/eff05b37-48bc-415c-8334-d61ede74520d">

**Comment by planbnet** [comment]
I've also been thinking about this quite a bit, but I never fully understood how it even works in the Livisi software. Maybe you can explain:

I have a room with a wall thermostat and a heating thermostat/actuator. Now I can push the button on any of these devices and it will toggle between manual and automatic. What exactly does this do? What does automatic even mean in Livisi? As far as I understand, schedules are also just automations that that the temperature to a specific value at a specific time? Does pushing the button just toggle this device or the whole room?

The screenshots you posted, are they from the thermostat device or the "virtual room climate" device?

**Comment by cagcoach** [comment]
the screenshots are from the device page.
<img width="873" alt="Bildschirmfoto 2024-02-11 um 12 51 51" src="https://github.com/planbnet/livisi_unofficial/assets/9169292/074099e1-ff83-4b14-82b3-73b7ca41c4ec">
Eventough if i remember correctly a read somewhere in the manual that all climate devices in a room are automatically synchronized. So i guess we would need to create individual rooms for each device if you want to control them individually in HA.
Sadly the room thermostat is the only livisi climate device i have thus i cannot validate that. My heater thermostats are Homematic.

I tried setting up a development environment yesterday, but failed doing so. I guess I have to configure ssh-debugging to debug directly on my HA-Raspi from my computer... if you have good hints or further reading on that, let me know...

**Comment by planbnet** [comment]
_So i guess we would need to create individual rooms for each device if you want to control them individually in HA._

No, that's not required. This integration creates a "Climate" device for each "Livisi Room", and a thermostat device (with temp and humidity sensors) for each Livisi Thermostat. The problem is, that the mode is set on the thermostat in Livisi. However, this does not really make sense, because even in the Livisi system this seems to be a per-room setting. I'll try to figure out how this is connected, so auto and manual modes can be supported in the integration..
