### ISSUE TITLE
There is no clima entity anymore after update from 1.7.4 to 1.9.1

### ISSUE THREAD

**Issue by dete75** [planbnet/livisi_unofficial#86]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4897
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.1.0), Studio Code Server (5.15.0), AdGuard Home (5.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Februar 2024 um 21:32
-- | --
current_recorder_run | 21. Februar 2024 um 12:11
estimated_db_size | 46.47 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

There is no longer any "climate" entity with which i can regulate the temperature.

### Reproduction steps

Under Livisi unoffical 1.7.4, there was an entity called climate.xxx for each room, where I could change the room temperature in the dashboard. 

After the update to 1.9.1, the thermostat tiles were inactive and the corresponding entities no longer existed.

### Debug logs

```text
I have reset the system to 1.7.4 via backup
```

**Comment by planbnet** [comment]
Please add logs. How am I supposed to help you withotu seeing what is wrong?

**Comment by dete75** [comment]
I'm sorry. I have restarted Home Assistant, updated to 1.9.1 again (the climate entities are inactive again) and attached the log file.
Thanks for your help :) 

[home-assistant_2024-02-22T10-00-15.391Z.log](https://github.com/planbnet/livisi_unofficial/files/14372289/home-assistant_2024-02-22T10-00-15.391Z.log)
![Screenshot 2024-02-22 105922](https://github.com/planbnet/livisi_unofficial/assets/157220366/b8952269-b247-4a23-a6e0-5123751c00c7)

**Comment by planbnet** [comment]
Thanks. Will be fixed in 1.9.2
Just waiting for confirmation for the other open issue to be resolved.
