### ISSUE TITLE
Livisi sent error code 3000

### ISSUE THREAD

**Issue by olli711** [planbnet/livisi_unofficial#87]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 36

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 115.4 GB
disk_used | 13.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.1.0), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Samba Backup (5.2.0), Samba share (12.3.0), motionEye (0.20.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 27
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Februar 2024 um 09:54
-- | --
current_recorder_run | 21. Februar 2024 um 13:26
estimated_db_size | 108.93 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After updating to version 1.9.1 I get the above error message. It appears very frequently

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.livisi
Source: custom_components/livisi/livisi_connector.py:168
Integration: Livisi Unofficial (documentation, issues)
First occurred: 13:27:03 (133 occurrences)
Last logged: 15:49:46

Livisi sent error code 3000

### Reproduction steps

1.
2.
3.
...
cannot reproduce

### Debug logs

```text
-
```

### Diagnostics dump

-

**Comment by planbnet** [comment]
Can you please generate a debug log? This finally seems to be the error code that is polluting the logs (now that I've added correct failure handling)

**Comment by olli711** [comment]
I have debug logging turned on. But how do I get the protocol? I have little idea about it.

**Comment by planbnet** [comment]
Is anything not working or is it just this error in the logs?

The motion sensors do just send events, you can use these events in automations (see device triggers) or use them to create your own binary sensors (which is a bit advanced and I don't really see the need for it tbh). As "motion" is not really a state but an event I think that's the better abstraction.

There was a PR where someone implemented this but it wouldn't work for me...

**Comment by olli711** [comment]
I haven't noticed anything not working yet. So far there are only the minutes. I had 133 entries in it. Unfortunately I have no idea about it, otherwise I would help where possible.

As for the sensors, I have various blueprints that trigger an action. One cool thing is that I could get a snapshot on my iPhone. Unfortunately I don't know how to do that, otherwise I would create an automation myself

**Comment by olli711** [comment]
I haven't noticed anything not working yet. So far there are only the log entries. I had 133 entries in it. Unfortunately I have no idea about it, otherwise I would help where possible.

As for the sensors, I have various blueprints that trigger an action. One cool thing is that I could get a snapshot on my iPhone. Unfortunately I don't know how to do that, otherwise I would create an automation myself

**Comment by olli711** [comment]
There was a PR where someone implemented this but it wouldn't work for me...

where can I find that

**Comment by DanielHabenicht** [comment]
@olli711 here you go: https://github.com/planbnet/livisi_unofficial/pull/64

**Comment by DanielHabenicht** [comment]
I also get the error code:
![image](https://github.com/planbnet/livisi_unofficial/assets/13590797/520fba48-f708-4c03-ba06-72c68402c98a)
Seems to be related to #62 and the statistics endpoint.

**Comment by planbnet** [comment]
Can you give me the full response for this request? Does this include *all* the device states or just the SHC?

**Comment by planbnet** [comment]
Taking a closer look at your data in #62 - is it possible that your SHC device is is a42d421e1ad9460da6b690ce09e780c9 and for v2 it's always 000...00
Maybe the endpoint isn't different but the id is?

**Comment by DanielHabenicht** [comment]
yes. already revising a PR stay tuned.

**Comment by DanielHabenicht** [comment]
> Can you give me the full response for this request? Does this include _all_ the device states or just the SHC?

All device states.
As you mentioned the SHC1 does not have a hardcoded id but uses its own.

**Comment by planbnet** [comment]
I've modified the pull request so it should work for both SHC types. Please check if it still works for you.
