### ISSUE TITLE
Livisi sent error code 2007 after token request

### ISSUE THREAD

**Issue by lines27** [planbnet/livisi_unofficial#91]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4963
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Easee EV Charger</summary>

component_version | 0.9.55
-- | --
reach_easee_cloud | ok
connected2stream | true

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 234.0 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.9.0), Studio Code Server (5.15.0), Node-RED (17.0.7), evcc (0.124.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. Februar 2024 um 10:03
-- | --
current_recorder_run | 23. Februar 2024 um 12:04
estimated_db_size | 171.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Just got two consecutive error messages:

2024-02-25 12:05:32.512 ERROR (MainThread) [custom_components.livisi] Livisi sent error code 2007 after token request
2024-02-25 12:05:32.513 ERROR (MainThread) [custom_components.livisi] Unexpected error fetching Livisi devices data:

### Reproduction steps

1. Lastest Version of Livisi 1.9.3
2.Two days after update and restart of HA
3.Correlation with other events not recognizable, no ation during the error period
...

### Debug logs

```text
2024-02-25 12:05:32.512 ERROR (MainThread) [custom_components.livisi] Livisi sent error code 2007 after token request
2024-02-25 12:05:32.513 ERROR (MainThread) [custom_components.livisi] Unexpected error fetching Livisi devices data:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/livisi/coordinator.py", line 69, in _async_update_data
return await self.async_get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/livisi/coordinator.py", line 98, in async_get_devices
devices = await self.aiolivisi.async_get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/livisi/livisi_connector.py", line 215, in async_get_devices
messages = await self.async_send_authorized_request("get", path="message")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/livisi/livisi_connector.py", line 108, in async_send_authorized_request
return await self._async_request(method, url, payload, auth_headers)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/livisi/livisi_connector.py", line 167, in _async_request
raise ErrorCodeException(response["errorcode"])
custom_components.livisi.livisi_errors.ErrorCodeException
```

### Diagnostics dump

see above

**Comment by planbnet** [comment]
Did the integration stop working afterwards or what's the problem?

**Comment by lines27** [comment]
I get the error messages every other day. Error messages always make me nervous. But since there are no resulting problems, I will close the topic.
