### ISSUE TITLE
Keep state of window sensor after restart of the SHC

### ISSUE THREAD

**Issue by DanielHabenicht** [planbnet/livisi_unofficial#92]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

After a restart of the SHC the window sensors always report "unavailable" until triggered again (opened or closed)
![image](https://github.com/planbnet/livisi_unofficial/assets/13590797/06ad3f51-c462-4679-b7a7-02df8bdcff4f)

### Describe the solution you'd like

It would be great if this add-in would keep the state of the last time the sensor was triggered and ignore the "Unavailable" state reported by the SHC.

### Describe alternatives you've considered

manually open and close the window when one is wondering why the heating system is not working

### Additional context

...

**Comment by planbnet** [comment]
No, I don't want this. If the SHC reports "Unavailable" I want the integration to reflect this. Otherwise, we would never detect problems when a sensor breaks.
If you want this, build an automation in Home Assistant to simulate this behavior.

**Comment by DanielHabenicht** [comment]
Would you reconsider this with different mechanisms to detect if somethings breaks? E.g. a timed delay (say 1 day of staying

**Comment by planbnet** [comment]
Maybe „unavailable“ is wrong. We could check if the SHC reports „Unknown“ instead of unavailable if the sensor really does not respond. I guess in the Livisi UI it reports „?“… 
I‘m reopening this to at least investigate the bug you mention.

**Comment by DanielHabenicht** [comment]
after the bugfix, it should be ok. The SHC keeps the state of the sensor if restarted via the API.

**Comment by planbnet** [comment]
I did not understand the problem correctly I guess. When adding new window sensors, they are reported as "?" in the Livisi UI, but not after a restart. So this was indeed just a bug - thanks for the fix.
