### ISSUE TITLE
format the values in the integration

### ISSUE THREAD

**Issue by ThMFlive** [planbnet/livisi_unofficial#99]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The values provided by livisi are displayed differently in different cards in the HA dashboard. The date displayed at the motion detector cannot be adjusted. Is it possible to format the values in the integration?

![Screenshot_20240315_165512_Home Assistant.jpg](https://github.com/planbnet/livisi_unofficial/assets/120195949/33013548-0227-4173-8ed9-64c13038b539)

![Screenshot_20240315_165532_Home Assistant.jpg](https://github.com/planbnet/livisi_unofficial/assets/120195949/235c77ed-3c20-48e2-b244-a85881955fe5)

### Describe the solution you'd like

Is it possible to format the values in the integration? Similar to the decimal places in temperature and humidity values.

### Describe alternatives you've considered

--

### Additional context

--

**Comment by planbnet** [comment]
This is not something an integration does. The cards do the formatting (which explains why it differs)
